import { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "@/components/theme-provider";
import { Noto_Sans_JP } from "next/font/google";
import { House } from "lucide-react";

const notoSansJp = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
});

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={notoSansJp.variable} suppressHydrationWarning>
      <body>
        <header>
          <div className="flex justify-end p-4">
            <Link href={"/home"} className="mx-6">
              <House />
            </Link>
            {/* アカウント表示 */}
            <Link href={"/api/auth/signout"}>ログアウト</Link>
          </div>
        </header>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
